// Package postman builds a Postman Collection v2.1 document from scanned routes.
package postman

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/Grshor/go-postman-66/internal/scan"
)

// Options tune the generated collection.
type Options struct {
	Name    string // collection name
	BaseURL string // value for the {{base_url}} variable
}

// Collection is the v2.1 document root.
type Collection struct {
	Info     info       `json:"info"`
	Variable []variable `json:"variable"`
	Item     []item     `json:"item"`
}

type info struct {
	Name        string `json:"name"`
	Schema      string `json:"schema"`
	Description string `json:"description,omitempty"`
}

type variable struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type item struct {
	Name    string  `json:"name"`
	Item    []item  `json:"item,omitempty"`
	Request request `json:"request,omitempty"`
}

type request struct {
	Method      string   `json:"method"`
	Header      []header `json:"header,omitempty"`
	URL         url      `json:"url"`
	Description string   `json:"description,omitempty"`
}

type header struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type url struct {
	Raw      string    `json:"raw"`
	Host     []string  `json:"host"`
	Path     []string  `json:"path"`
	Variable []pathVar `json:"variable,omitempty"`
}

type pathVar struct {
	Key string `json:"key"`
}

const schema = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"

// Build renders routes as a collection grouped by Go package.
func Build(routes []scan.Route, opt Options) (*Collection, error) {
	if strings.TrimSpace(opt.Name) == "" {
		opt.Name = "API"
	}
	if strings.TrimSpace(opt.BaseURL) == "" {
		opt.BaseURL = "http://localhost:8080"
	}

	c := &Collection{
		Info: info{
			Name:        opt.Name,
			Schema:      schema,
			Description: "Generated by go-postman-66 from Go route registrations.",
		},
		Variable: []variable{{Key: "base_url", Value: opt.BaseURL}},
	}

	byPkg := map[string][]scan.Route{}
	var order []string
	for _, r := range routes {
		if _, seen := byPkg[r.Package]; !seen {
			order = append(order, r.Package)
		}
		byPkg[r.Package] = append(byPkg[r.Package], r)
	}
	sort.Strings(order)
	for _, rs := range byPkg {
		sort.Slice(rs, func(i, j int) bool {
			a, b := rs[i], rs[j]
			if a.File != b.File {
				return a.File < b.File
			}
			if a.Line != b.Line {
				return a.Line < b.Line
			}
			return a.Path < b.Path
		})
	}

	for _, pkg := range order {
		folder := item{Name: pkg}
		for _, r := range byPkg[pkg] {
			segs := pathSegments(r.Path)
			folder.Item = append(folder.Item, item{
				Name: requestName(r),
				Request: request{
					Method:      r.Method,
					Description: r.Desc,
					URL: url{
						Raw:      "{{base_url}}" + ensureSlash(r.Path),
						Host:     []string{"{{base_url}}"},
						Path:     segs,
						Variable: pathVars(segs),
					},
				},
			})
		}
		c.Item = append(c.Item, folder)
	}
	return c, nil
}

// Render marshals the collection with stable, human-friendly indentation.
func Render(c *Collection) ([]byte, error) {
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal collection: %w", err)
	}
	return append(b, '\n'), nil
}

func requestName(r scan.Route) string {
	name := ensureSlash(r.Path)
	if r.Method != "" {
		return r.Method + " " + name
	}
	return name
}

func ensureSlash(p string) string {
	if !strings.HasPrefix(p, "/") {
		return "/" + p
	}
	return p
}

// pathSegments converts a Go router pattern to Postman path segments:
// {id} and :id both become :id; {path...} becomes :path.
func pathSegments(pattern string) []string {
	pattern = strings.Trim(pattern, "/")
	if pattern == "" {
		return []string{}
	}
	parts := strings.Split(pattern, "/")
	for i, p := range parts {
		switch {
		case strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}") && len(p) > 2:
			inner := strings.TrimSuffix(strings.TrimPrefix(p, "{"), "}")
			parts[i] = ":" + strings.TrimSuffix(inner, "...")
		case strings.HasPrefix(p, ":"):
			// already Postman-style
		}
	}
	return parts
}

func pathVars(segs []string) []pathVar {
	var vars []pathVar
	for _, s := range segs {
		if strings.HasPrefix(s, ":") {
			vars = append(vars, pathVar{Key: strings.TrimPrefix(s, ":")})
		}
	}
	return vars
}
